# Generated by Django 3.0 on 2019-12-28 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=10, unique=True)),
                ('rolled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=10, unique=True)),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='prizeWheelApp.Prize')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='prizeWheelApp.User')),
            ],
        ),
    ]
