# Generated by Django 3.0 on 2019-12-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizeWheelApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='participated',
            field=models.BooleanField(default=False),
        ),
    ]
