# Generated by Django 3.0 on 2019-12-23 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prizeWheelApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winner',
            old_name='userID',
            new_name='phoneNumber',
        ),
    ]
