# Generated by Django 3.0 on 2019-12-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizeWheelApp', '0002_user_participated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.IntegerField(),
        ),
    ]
