# Generated by Django 3.0 on 2019-12-23 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prizeWheelApp', '0002_auto_20191223_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winner',
            old_name='prizeID',
            new_name='prize',
        ),
    ]
